version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12 
      python: 3.x 
    commands:
      - pip3 install --upgrade awscli 
      - pip3 install aws-sam-cli
  build:
    commands:
      # Build and deploy the Rubric Lambda function
      - cd rubric/src
      - npm install
      - npm test
      - rm -rf node_modules
      - rm -rf __tests__
      - rm -f yarn.lock package-lock.json
      - npm install --production
      - pip install --upgrade awscli
      - pwd
      - cd ../ 
      - pwd
      - sam package --template-file template.yaml --s3-bucket grindywiz --output-template-file rubric-packaged.yaml
      - sam deploy --template-file rubric-packaged.yaml --stack-name grindywiz-rubric-lambda --capabilities CAPABILITY_IAM --region us-east-1
      # Build the Keybase bot daemon image
      # We save kbd as an artifact and the CodePipelin deploys
      - cd ../bot/
      - docker build -t "keybase-docker" .
      - docker save -o kbd.tar "keybase-docker"
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
     - kbd.tar
