version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12 
      python: 3.x 
    commands:
      - pip3 install --upgrade awscli 
      - pip3 install aws-sam-cli
  build:
    commands:
      # Build and deploy the Rubric Lambda function
      - cd rubric/src
      - cp ../../bot/src/problems.json .
      - npm install
      - npm test
      - rm -rf node_modules
      - rm -rf __tests__
      - rm -f yarn.lock package-lock.json
      - npm install --production
      - pip install --upgrade awscli
      - pwd
      - cd ../ 
      # Now we are in rubric/
      - pwd
      - sam package --template-file template.yaml --s3-bucket grindywiz --output-template-file rubric-packaged.yaml
      - sam deploy --template-file rubric-packaged.yaml --stack-name grindywiz-rubric-lambda --capabilities CAPABILITY_IAM --region us-east-1
      # Build the Keybase bot daemon image
      - cd ../bot/src
      - npm install
      - npm install -g typescript
      - tsc
      - cd ../
      # Now we are in bot/
      - docker build -t "keybase-docker" .
      - mkdir /usr/share/bot/{$CODEBUILD_BUILD_ID}
      - docker save -o /usr/share/bot/{$CODEBUILD_BUILD_ID}/kbd.tar "keybase-docker"
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
#  files:
#     - bot/kbd.tar
