AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Rubric grader for JavaScript code 

Resources:
  RubricLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: handler.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Role: !GetAtt RubricLambdaExecutionRole.Arn
      Tracing: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0b6a0a7984258dd98 # important: no outbound internet access
        SubnetIds: 
          - subnet-0640b3b0e9e1db0a7

  RubricLambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 
              - lambda.amazonaws.com
          Action: 
            - "sts:AssumeRole"
      Policies:
      - PolicyName: accessRubricHmacSecret
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "secretsmanager:GetSecretValue"
      - PolicyName: rubricLambdaLogs 
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
            - "xray:GetSamplingRules"
            - "xray:GetSamplingTargets"
            - "xray:GetSamplingStatisticSummaries"
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
      - PolicyName: rubricDeployment
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "iam:GetRole"      
            - "iam:GetRole"
            - "iam:CreateRole"
            - "iam:PassRole"
            - "iam:DeleteRole"
            - "iam:UpdateAssumeRolePolicy"
            - "iam:GetRolePolicy"
            - "iam:PutRolePolicy"
            - "iam:AttachRolePolicy"
            - "iam:DetachRolePolicy"
            - "iam:DeleteRolePolicy"
            - "iam:TagRole"
            - "iam:UntagRole"
