AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Rubric grader for JavaScript code 

Resources:
  GrindyWizRubricLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: handler.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Role: !GetAtt GrindyWizRubricLambdaExecutionRole.Arn
      Tracing: Active
      VpcConfig:
        SecurityGroupIds:
          - sg-0b6a0a7984258dd98 # important: no outbound internet access
        SubnetIds: 
          - subnet-0640b3b0e9e1db0a7

  GrindyWizRubricLambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 
              - lambda.amazonaws.com
          Action: 
            - "sts:AssumeRole"
      Policies:
      - PolicyName: accessRubricHmacSecret
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "secretsmanager:GetSecretValue"
            Resource:
            - "arn:aws:secretsmanager:us-east-1:589230162435:secret:grindywiz_rubric_hmac-4Ztwyo"
      - PolicyName: rubricLambdaLogs 
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
            - "xray:GetSamplingRules"
            - "xray:GetSamplingTargets"
            - "xray:GetSamplingStatisticSummaries"
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource:
            - "*"
      - PolicyName: "AWSLambdaVPCAccessExecutionRole"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - "ec2:CreateNetworkInterface"
            - "ec2:DescribeNetworkInterfaces"
            - "ec2:DetachNetworkInterface"
            - "ec2:DeleteNetworkInterface"
            Resource:
            - "*"
      - PolicyName: rubricDeployment
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "iam:GetRole"      
            - "iam:GetRole"
            - "iam:CreateRole"
            - "iam:PassRole"
            - "iam:DeleteRole"
            - "iam:UpdateAssumeRolePolicy"
            - "iam:GetRolePolicy"
            - "iam:PutRolePolicy"
            - "iam:AttachRolePolicy"
            - "iam:DetachRolePolicy"
            - "iam:DeleteRolePolicy"
            - "iam:TagRole"
            - "iam:UntagRole"
            Resource:
            - !Sub "arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-GrindyWizRubricLambdaRole-*"
            - !Sub "arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-GrindyWizRubricLambdaExecutionRole-*"
            - !Sub "arn:aws:sts::${AWS::AccountId}:assumed-role/codebuild-GrindyWiz-codebuild-service-role/*"
